# Generated by Django 5.1 on 2024-08-12 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_exams', '0005_remove_mocktest_link_alter_exam_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='link',
            field=models.CharField(default='youtube.com', max_length=255),
        ),
    ]
