# Generated by Django 5.1 on 2024-08-12 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_exams', '0007_remove_exam_link_mocktest_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mocktest',
            name='link',
            field=models.URLField(default='youtube.com', max_length=255),
        ),
    ]
