# Generated by Django 5.1 on 2024-08-11 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_exams', '0002_remove_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
