# Generated by Django 5.1 on 2024-08-11 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_exams', '0004_mocktest_link_alter_exam_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mocktest',
            name='link',
        ),
        migrations.AlterField(
            model_name='exam',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
