# Generated by Django 5.1 on 2024-08-11 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_exams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
