# Generated by Django 5.1 on 2024-08-11 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_exams', '0003_alter_exam_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='mocktest',
            name='link',
            field=models.URLField(default='http://example.com'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='description',
            field=models.TextField(),
        ),
    ]
