# Generated by Django 4.2.11 on 2024-10-29 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_exams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='characteristic_1',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Clarity of Concepts (1-5)'),
        ),
        migrations.AlterField(
            model_name='review',
            name='characteristic_2',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Difficulty Appropriateness (1-5)'),
        ),
        migrations.AlterField(
            model_name='review',
            name='characteristic_3',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Relevance to Exam Pattern (1-5)'),
        ),
        migrations.AlterField(
            model_name='review',
            name='characteristic_4',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Quality of Questions (1-5)'),
        ),
        migrations.AlterField(
            model_name='review',
            name='characteristic_5',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Time Management (1-5)'),
        ),
        migrations.AlterField(
            model_name='review',
            name='characteristic_6',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Overall Preparation Value (1-5)'),
        ),
        migrations.AlterField(
            model_name='review',
            name='characteristic_7',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Likelihood of Recommending (1-5)'),
        ),
    ]
