# Generated by Django 5.0.8 on 2024-08-07 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mocktest',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
    ]
