# Generated by Django 5.0.8 on 2024-08-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_exams', '0002_mocktest_is_premium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
