# Generated by Django 5.1 on 2024-08-12 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_exams', '0006_exam_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='link',
        ),
        migrations.AddField(
            model_name='mocktest',
            name='link',
            field=models.CharField(default='youtube.com', max_length=255),
        ),
    ]
