# Generated by Django 5.1.2 on 2024-10-13 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_exams', '0008_alter_mocktest_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('question_quality', models.PositiveIntegerField(default=0)),
                ('topic_hardness', models.PositiveIntegerField(default=0)),
                ('preparation_level', models.PositiveIntegerField(default=0)),
                ('time_management', models.PositiveIntegerField(default=0)),
                ('difficulty_balance', models.PositiveIntegerField(default=0)),
                ('syllabus_coverage', models.PositiveIntegerField(default=0)),
                ('practical_relevance', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mock_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='app_exams.mocktest')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('mock_test', 'student')},
            },
        ),
    ]
