# Generated by Django 5.1.2 on 2024-10-22 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_exams', '0009_mocktest_description_alter_exam_description_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
